param([switch]$Local)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $true
Set-StrictMode -Version Latest

$root = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
if ($Local) {
    $hostTriple = ((& rustc -vV | Select-String '^host: ').Line -replace '^host: ', '')
    $arch = switch ($hostTriple) {
        'x86_64-pc-windows-msvc' { 'x64' }
        'aarch64-pc-windows-msvc' { 'arm64' }
        default { throw "Unsupported Rust host: $hostTriple. Install native MSVC Rust." }
    }
    $cache = Join-Path $root 'build/windows-deps'
    New-Item -ItemType Directory -Force $cache | Out-Null
    git -C $root submodule update --init --recursive
} else {
    $arch = $env:PACKAGE_ARCH
    $cache = $env:RUNNER_TEMP
}

# The runner's standalone LLVM matches the native Rust host architecture.
# VsDevShell prepends x64 LLVM to PATH even on ARM64: those compilers can
# cross-compile, but bindgen cannot load their x64 libclang.dll into ARM64 Rust.
$libclangPath = if ($env:LIBCLANG_PATH) { $env:LIBCLANG_PATH } else { Join-Path $env:ProgramFiles 'LLVM\bin' }
if (-not (Test-Path (Join-Path $libclangPath 'libclang.dll'))) {
    throw "Native libclang.dll was not found in $libclangPath. Install LLVM (winget install --id LLVM.LLVM --exact), then rerun setup."
}

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vs = & $vswhere -latest -products '*' -property installationPath
if (-not $vs) { throw 'Visual Studio C++ build tools were not found' }
# VsDevShell supports x64 host tools, including under Windows ARM64 emulation.
$vsArch = if ($arch -eq 'x64') { 'amd64' } else { $arch }
& "$vs\Common7\Tools\Launch-VsDevShell.ps1" -Arch $vsArch -HostArch amd64 -SkipAutomaticLocation
$env:PATH = "$libclangPath;$env:PATH"
foreach ($tool in @('clang.exe', 'clang++.exe', 'cmake.exe', 'ninja.exe', 'rc.exe')) {
    Get-Command $tool -ErrorAction Stop | Out-Null
}

$vcpkg = Join-Path $cache 'faxe-vcpkg'
if (-not (Test-Path "$vcpkg/.git")) {
    git clone --filter=blob:none https://github.com/microsoft/vcpkg.git $vcpkg
}
git -C $vcpkg checkout 04a9d8e5212d01ee1dd9478eadd9caade4f8b0d4
& "$vcpkg\bootstrap-vcpkg.bat" -disableMetrics
$installed = Join-Path $cache 'faxe-vcpkg-installed'
$triplet = "$arch-windows"
& "$vcpkg\vcpkg.exe" install --triplet $triplet --host-triplet $triplet `
    "--x-manifest-root=$root\packaging\windows" "--x-install-root=$installed"
$prefix = Join-Path $installed $triplet
$pkgconf = Get-ChildItem "$prefix\tools" -Recurse -Filter pkgconf.exe | Select-Object -First 1
if (-not $pkgconf) { throw 'vcpkg did not install pkgconf' }
$clang = (Get-Command clang.exe -ErrorAction Stop).Source
$clangxx = (Get-Command clang++.exe -ErrorAction Stop).Source

$settings = @{
    CC = $clang
    CXX = $clangxx
    LIBCLANG_PATH = $libclangPath
    PKG_CONFIG = $pkgconf.FullName
    PKG_CONFIG_PATH = "$prefix\lib\pkgconfig;$prefix\share\pkgconfig"
    FAXE_VCPKG_PREFIX = $prefix
    PATH = "$prefix\bin;$env:PATH"
}
foreach ($name in @('INCLUDE', 'LIB', 'LIBPATH', 'WindowsSdkDir', 'WindowsSDKVersion', 'VCToolsRedistDir')) {
    $settings[$name] = [Environment]::GetEnvironmentVariable($name)
}
foreach ($entry in $settings.GetEnumerator()) {
    if (-not $entry.Value) { throw "Missing Windows build setting $($entry.Key)" }
    if (-not $Local) {
        "$($entry.Key)=$($entry.Value)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    }
}
if ($Local) {
    $config = Join-Path $root '.cargo/config.toml'
    $marker = '# Generated by scripts/ci/setup-windows.ps1 -Local'
    if ((Test-Path $config) -and -not (Get-Content $config -Raw).StartsWith($marker)) {
        throw "Preserving existing $config. Merge the Windows environment settings manually or move it aside and rerun setup."
    }
    if (Test-Path (Join-Path $root '.cargo/config')) {
        throw 'Existing .cargo/config takes precedence over config.toml; move or merge it before rerunning setup.'
    }
    New-Item -ItemType Directory -Force (Split-Path $config) | Out-Null
    # Cargo replaces PATH when launching build scripts and executables on Windows.
    # Keep the native tool path separately for our build scripts and run wrapper.
    $settings['FAXE_BUILD_PATH'] = $settings['PATH']
    $settings.Remove('PATH')
    $runner = @((Get-Process -Id $PID).Path, '-NoProfile', '-File', (Join-Path $root 'scripts/run-windows.ps1'))
    $lines = @($marker, '# Machine-specific paths; this file is ignored by Git.',
        "[target.$hostTriple]", "runner = $(ConvertTo-Json -InputObject $runner -Compress)", '[env]')
    foreach ($entry in ($settings.GetEnumerator() | Sort-Object Key)) {
        $value = ConvertTo-Json -InputObject ([string]$entry.Value) -Compress
        $lines += "$($entry.Key) = $value"
    }
    $lines | Set-Content -Path $config -Encoding utf8
    Write-Host "Windows dependencies configured in $config. Run cargo run from the repository."
}
